development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://kwxdkkmjnfxpjr:667390fb1a3a4845737a887cee53ce4cd36437e5f6bd60db0f54b978eb28ed20@ec2-54-204-39-46.compute-1.amazonaws.com:5432/dbddb2lj7at4pj
  
